### ISSUE TITLE
Error 401: Unauthorized

### ISSUE THREAD

**Issue by megaslothy** [martsve/mkm_api#1]
I have configured App Token, App Secret, Access Token and Access Token Secret in tokens.txt file. My app is Dedicated. I always get the error 401: Unauthorized. Is it necessary to set up something else?

Thanks

**Comment by martsve** [comment]
There shouldn't be other set up necessary. Some guesses to what might be wrong:
- White spaces at the end of the lines in tokens.txt file file (tabs, spaces)  - I checked the source, and it's possible it trimmed it in the wrong order. I've updated the code, so you can re-download the tool and check if the problem persists.
- Are you sure the corrects tokens.txt is being loaded? Did you place it in the same folder as mkm.exe? 
- Did you provide the correct tokens? They should be listed in the same order as written on your account page on MKM.
- You might have pasted the tokens incorrectly. When you copy from the webpage, whitespace is lacking between the text and the tokens. Make sure no additional letters are present.

I updated the code, so try to re-download it. It now tells you what tokens it tried to use when you receive a 401 error.

**Comment by megaslothy** [comment]
I downloaded the app again and have checked (and typed) the token information but still getting the same error. I can't see the message with error tokens also. The tokens.txt file that I use is the one generated when executing mkm.exe without tokens.txt.

**Comment by martsve** [comment]
Did you use this link to download the new version?

https://github.com/martsve/mkm_api/archive/master.zip

Make sure you overwrite the old one. I just tried downloading it, and exectuing with a mock-file and get this display:

```
  D:\>mkm get account
  Error: The remote server returned an error: (401) Unauthorized.
  App token = 'a'
  App secret = 'b'
  Access token = 'c'
  Access token secret = 'd'
```

**Comment by megaslothy** [comment]
I used the correct link and re-downloaded again from your message. Still getting the same error and don't see the error tokens. 

```
C:\mkm_api-master>dir
 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 7464-2AD4

 Directorio de C:\mkm_api-master

26/10/2015  23:16    <DIR>          .
26/10/2015  23:16    <DIR>          ..
26/10/2015  08:49             2.518 .gitattributes
26/10/2015  08:49             3.138 .gitignore
26/10/2015  23:16    <DIR>          examples
26/10/2015  08:49            18.027 LICENSE
26/10/2015  08:49            11.776 mkm.exe
26/10/2015  08:49             1.466 README.md
26/10/2015  23:16    <DIR>          source
26/10/2015  23:13               104 tokens.txt
               6 archivos         37.029 bytes
               4 dirs  18.802.454.528 bytes libres

C:\mkm_api-master>mkm get account
Error: Error en el servidor remoto: (401) No autorizado.

C:\mkm_api-master>
```

And the tokens.txt:

```
URL=https://www.mkmapi.eu/ws/v1.1/
App token=a
App secret=b
Access token=c
Access token secret=d
```

No idea what it's happening

**Comment by martsve** [comment]
Allright, the language made it skip the error.. I corrected it to check for error code, and it should now display the token used when it fails.

**Comment by megaslothy** [comment]
Now It displays the token used but it is exactly the token information I have in my MKM account page and I still have the 401 Error.

**Comment by martsve** [comment]
Ok.. 
- You are sure the app type is listed as Dedicated?
- Try to Renew tokens
- I updated the program force en-Gb culture. Maybe your local-language settings somehow messes up the OAuth headers. I kind of doubt it, but let's see..

**Comment by megaslothy** [comment]
Worked!

The app  is Dedicated and I renewed tokens before so it seems to be some problem with my local language.

Thanks!!
